obstacle_range: 1.0         ##
raytrace_range: 1.5         ##
footprint: [[0.3, 0.15], [0.3, -0.15], [-0.35, -0.15], [-0.35, 0.15]]
# robot_radius: 0.3

static_layer:
 enable:true

obstacle_layer:
 enabled:true
 track_unknown_space:true
 combination_method:1
 obstacle_range:2.5
 raytrace_range:3.0

inflation_radius: 0.03
max_obstacle_height: 1.0
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 5.0}
#observation_sources: faceLaserScan leftLaserScan rightLaserScan
#faceLaserScan: {data_type: LaserScan, topic: /faceLaserScan, marking: true, clearing: true, expected_update_rate: 3.3}
#leftLaserScan: {data_type: LaserScan, topic: /leftLaserScan, marking: true, clearing: true, expected_update_rate: 3.3}
#rightLaserScan: {data_type: LaserScan, topic: /rightLaserScan, marking: true, clearing: true, expected_update_rate: 3.3}
